@startuml
skinparam classAttributeIconSize 0

package GUI{
    abstract class AbstractRouter{
        + load(String pathFXML) : Parent
        + changeView(String pathFXML, ActionEvent event)
        + adminRestricted(String pathFXML, ActionEvent event)
        + studentRestricted(String pathFXML, ActionEvent event)
        + partnerRestricted(String pathFXML, ActionEvent event)
    }
    class HomeAdminController{
            - bienvenueL : Label
            + managePendingServices(ActionEvent event)
            + seeAllServices(ActionEvent event)
            + logout(ActionEvent event)
            + initialize(URL location, RessourceBundle resources)
    }
    class HomeStudentController{
            - bienvenueL : Label
            + myServices(ActionEvent event)
            + seeAllServices(ActionEvent event)
            + proposeService(ActionEvent event)
            + requestService(ActionEvent event)
            + logout(ActionEvent event)
            + initialize(URL location, RessourceBundle resources)
    }
    class ProposeAskServiceController{
        - name : TextField
        - category : TextField
        - description : TextField
        - cost : TextField

        + submitProposeService(ActionEvent event)
        + submitAskService(ActionEvent event)
        + updateService(ActionEvent event)
        + cancel(ActionEvent event)
    }
    class HistoricController{
            - services : Service[]

            + getMyServicesBought(ActionEvent event)
            + cancel(ActionEvent event)
        }

    class myServicesController{
        - services : Service[]

        + viewService()
        + back(ActionEvent event)
    }

    class viewServiceController{
        - service : Service
        - validateService : Button
        - buyService : Button
        - applyForService : Button
        - updateService : Button
        - deleteService : Button
        - viewFeedbacks : Button
        
        
        + validateService(ActionEvent event)
        + viewFeedbacks(ActionEvent event)
        + updateService(ActionEvent event)
        + deleteService(ActionEvent event)
        + buyService(ActionEvent event)
        + applyForService(ActionEvent event)
        + back(ActionEvent event)
    }

    class allServicesController{
        - services : Service[]
        - keyword : TextField
        - category : DropBox
        - askedServices : CheckBox
        - proposedServices : CheckBox

        + seeAllServices(ActionEvent event)
        + seeProposedServices(ActionEvent event)
        + seeAskedServices(ActionEvent event)
        + viewService(ActionEvent event)
        + searchService(ActionEvent event)
        + back(ActionEvent event)
        + initialize(URL location, RessourceBundle resources)
        + back(ActionEvent event)
    }


    class ServiceRouter{
        + VIEW_SERVICE_FXML_PATH : String = "views/service/view_service.fxml"
        + PROPOSE_ASK_SERVICE_FXML_PATH : String = "views/service/propose_ask_service.fxml"
        + MY_SERVICES_FXML_PATH : String = "views/service/propose_ask_service.fxml"
        + ALL_SERVICES_FXML_PATH : String = "views/service/all_services.fxml"
        + SERVICES_BOUGHT_FXML_PATH : String = "views/service/services_bought.fxml"
        + getInstance() : ServiceRouter
        + login(ActionEvent event )
    }

    AbstractRouter <|-right- ServiceRouter


    AbstractRouter <-- HomeAdminController
    AbstractRouter <-- HomeStudentController
    AbstractRouter <-- allServicesController
    AbstractRouter <-- HistoricController
    AbstractRouter <-- viewServiceController
    AbstractRouter <-- myServicesController
    AbstractRouter <-- ProposeAskServiceController

    allServicesController <.. AbstractRouter : creates
    HistoricController <.. AbstractRouter : creates
    HomeAdminController <.. AbstractRouter : creates
    HomeStudentController <.. AbstractRouter : creates
    ProposeAskServiceController <.. AbstractRouter : creates
    myServicesController <.. AbstractRouter : creates
    viewServiceController <.. AbstractRouter : creates




}
package BusinessLogic{
    class FacadeService{
      
        + seeAllServices(int typeService) : Service[]
        + seePendingServices() : Service[]
        + searchService(String keyword, String category) : Service[]
        + getMyServicesBought() : Service[]
        + validateService()
        + updateService(String name,String category, String description, int cost)
        + submitProposeService(String name,String category, String description, int cost)
        + submitAskService(String name,String category, String description, int cost)
        + buyService(Service s)
        + updateService(String name,String category, String description, int cost, Service service)
        + applyForService()
        + deleteService()
        + getInstance() : FacadeService
    }

    abstract class Factory{
        + CreateServiceDAO() : ServiceDAO
    }
    class MySQLFactory{
        - db : Connection
        + getInstance() : MySQLFactory
        + CreateServiceDAO() : UserDAO
        - openConnection()
        - closeConnection()
    }


    Factory <.. FacadeService : creates
    Factory <|-left- MySQLFactory

    FacadeService <-up- allServicesController
    FacadeService <-up- HistoricController
    FacadeService <-up- viewServiceController
    FacadeService <-up- myServicesController
    FacadeService <-up- ProposeAskServiceController



}

package DAO{

    abstract class ServiceDAO{
        + seePendingServices() : Service[]
        + seeProposedServices() : Service[]
        + seeAskedServices() : Service[]
        + searchService(String keyword, String category) : Service[]
        + updateService(String name,String category, String description, int cost, Service service)
        + validateService()
        + updateService(String name,String category, String description, int cost)
        + submitProposeService(String name,String category, String description, int cost)
        + submitAskService(String name,String category, String description, int cost)
        + deleteService()
    }

    class MySQLServiceDAO{
        - DB : Connection
        + {static} getInstance() : MySQLPartnerDAO
        + seeAllServices() : Service[]
        + seeProposedServices() : Service[]
        + seeAskedServices() : Service[]
        + updateService(String name,String category, String description, int cost, Service service)
        + searchService(String keyword, String category) : Service[]
        + validateService()
        + updateService(String name,String category, String description, int cost)
        + submitProposeService(String name,String category, String description, int cost)
        + submitAskService(String name,String category, String description, int cost)
        + deleteService()
    }

    MySQLServiceDAO --|> ServiceDAO
    MySQLServiceDAO <.right. MySQLFactory : creates

    ServiceDAO <-right- FacadeService
}



@enduml