@startuml
autonumber
actor Partner
seeFeedbacksServiceController -> FacadeFeedback : getInstance()
activate seeFeedbacksServiceController
activate FacadeFeedback
FacadeFeedback -> MySQLFactory : getInstance()
activate MySQLFactory
FacadeFeedback -> MySQLFactory : createFeedbackDAO()
MySQLFactory -> MySQLFeedbackDAO : getInstance()
deactivate MySQLFactory
activate MySQLFeedbackDAO
deactivate MySQLFeedbackDAO
seeFeedbacksServiceController -> seeFeedbacksServiceController : initialize(location,ressources)
seeFeedbacksServiceController -> FacadeFeedback : getFeedbacks(service)
FacadeFeedback -> MySQLFeedbackDAO : getFeedbacks(service)
database DB
MySQLFeedbackDAO -> DB : Query Information
activate DB
DB --> MySQLFeedbackDAO : Result Set
deactivate DB
MySQLFeedbackDAO --> FacadeFeedback : List of feedbacks
deactivate MySQLFeedbackDAO
FacadeFeedback --> seeFeedbacksServiceController : List of feedbacks
deactivate FacadeFeedback
seeFeedbacksServiceController -> seeFeedbacksServiceController : Update the view
seeFeedbacksServiceController --> Partner : Display the view with the feedbacks
deactivate seeFeedbacksServiceController
@enduml