@startuml
autonumber
actor Partner
seeFeedbacksServiceController -> FacadeFeedback : getInstance()
activate seeFeedbacksServiceController
activate FacadeFeedback
FacadeFeedback -> MySQLFactory : getInstance()
activate MySQLFactory
MySQLFactory -> MySQLFeedbackDAO : getInstance()
deactivate MySQLFactory
activate MySQLFeedbackDAO
MySQLFeedbackDAO -> FeedbackDAO : createFeedbackDAO()
deactivate MySQLFeedbackDAO
activate FeedbackDAO
seeFeedbacksServiceController -> seeFeedbacksServiceController : initialize(location,ressources)
seeFeedbacksServiceController -> FacadeFeedback : getFeedbacks(service)
FacadeFeedback -> FeedbackDAO : getFeedbacks(service)
database DB
FeedbackDAO -> DB : Query Information
activate DB
DB --> FeedbackDAO : Result Set
deactivate DB
FeedbackDAO --> FacadeFeedback : List of feedbacks
deactivate FeedbackDAO
FacadeFeedback --> seeFeedbacksServiceController : List of feedbacks
deactivate FacadeFeedback
seeFeedbacksServiceController -> seeFeedbacksServiceController : Update the view
seeFeedbacksServiceController --> Partner : Display the view with the feedbacks
deactivate seeFeedbacksServiceController
@enduml