@startuml
autonumber
actor Partner
AddUpdateJobOfferController -> FeedBackRouter : getInstance()
activate AddUpdateJobOfferController
activate FeedBackRouter
AddUpdateJobOfferController -> FacadeJob : getInstance()
activate FacadeJob
FacadeJob -> MySQLFactory : getInstance()
activate MySQLFactory
FacadeJob -> MySQLFactory : createJobDAO()

MySQLFactory -> MySQLJobDAO : getInstance()
deactivate MySQLFactory

activate MySQLJobDAO

deactivate MySQLJobDAO
AddUpdateJobOfferController --> Partner : Display the view
activate Partner
Partner -> AddUpdateJobOfferController : Enter job information, push the button add
AddUpdateJobOfferController -> AddUpdateJobOfferController : addJobOffer(event)
AddUpdateJobOfferController -> FacadeJob : addJobOffer(String jobTitle,...,String contactInfo)
alt bad info case
    FacadeJob --> AddUpdateJobOfferController : Throw error
    AddUpdateJobOfferController --> Partner : Ask to enter good information
else good info case
    FacadeJob -> MySQLJobDAO : addJobOffer(String jobTitle,...,String contactInfo)
    deactivate FacadeJob
    database DB
    MySQLJobDAO -> DB : Query Information
    deactivate MySQLJobDAO
    AddUpdateJobOfferController --> Partner : Display the success of the action
    Partner -> AddUpdateJobOfferController : Click "ok"
    deactivate Partner
    AddUpdateJobOfferController -> FeedBackRouter : changeView(UserRouter.HOME_PARTNER_PATH_FXML)
    deactivate AddUpdateJobOfferController
    deactivate FeedBackRouter
end
@enduml