@startuml

actor User
autonumber
alt Login


    LoginController -> FacadeUser : getInstance()
    activate LoginController
    participant RouterUser
    activate FacadeUser
    FacadeUser -> MySQLFactory : getInstance()
    activate MySQLFactory
    MySQLFactory -> MySQLUserDAO : getInstance()
    deactivate MySQLFactory
    activate MySQLUserDAO
    MySQLUserDAO -> UserDAO : createUserDao()
    deactivate MySQLUserDAO
    activate UserDAO
    LoginController -> RouterUser : getInstance()
    activate RouterUser
    LoginController --> User : Display view
    activate User
    User -> LoginController : Enter his information
    LoginController -> LoginController : login(event)
    participant Session
    LoginController-> FacadeUser : login(email,password)

    FacadeUser -> Session : getInstance()
    activate Session
    FacadeUser -> UserDAO : searchUser(email,password)
    database DB
    UserDAO -> DB : Query information
    activate DB
    DB --> UserDAO : Result Set
    deactivate DB
  alt login successful
    UserDAO --> FacadeUser : user
    FacadeUser -> Session : setCurrentUser(user)
    deactivate Session
    FacadeUser -> RouterUser : changeView(pathFXML,event)
    deactivate RouterUser
  else login failed
    UserDAO --> FacadeUser : Exception
    deactivate UserDAO
    FacadeUser --> LoginController : Exception
    deactivate FacadeUser
    LoginController --> User : Ask to enter good credentials
    deactivate LoginController
    deactivate User
end
end
@enduml
