@startuml
autonumber
actor User
seeNotificationController -> FacadeNotification : getInstance()
activate seeNotificationController
activate FacadeNotification
FacadeNotification -> NotificationDAO : getInstance()
activate NotificationDAO
NotificationDAO -> Factory : getInstance()
activate Factory
Factory --> MySQLFactory : MySQLFactory()
deactivate Factory
activate MySQLFactory
NotificationDAO -> MySQLFactory : createNotificationDAO()
deactivate NotificationDAO
MySQLFactory --> MySQLNotificationDAO : MySQLNotificationDAO()
deactivate MySQLFactory
activate MySQLNotificationDAO
deactivate MySQLNotificationDAO
seeNotificationController -> seeNotificationController : initialize(location,ressources)
seeNotificationController -> FacadeNotification : getNotification(User)
FacadeNotification-> MySQLNotificationDAO : getNotifications(User)
database DB
MySQLNotificationDAO -> DB : Query Information
activate DB
DB --> MySQLNotificationDAO : Result Set
deactivate DB
MySQLNotificationDAO --> FacadeNotification : List of notifications
deactivate MySQLNotificationDAO
FacadeNotification --> seeNotificationController : List of notifications
deactivate FacadeNotification
seeNotificationController -> seeNotificationController : Update the view
seeNotificationController --> User : Display notifications
deactivate seeNotificationController
@enduml