@startuml
autonumber
actor Admin
AddUpdatePartnerController -> UserRouter : getInstance()
activate AddUpdatePartnerController
activate UserRouter
AddUpdatePartnerController -> FacadePartner : getInstance()
activate FacadePartner
FacadePartner -> PartnerDAO : getInstance()
activate PartnerDAO
PartnerDAO -> Factory : getInstance()

activate Factory
Factory --> MySQLFactory : MySQLFactory()
deactivate Factory
activate MySQLFactory
PartnerDAO -> MySQLFactory : createPartnerDao()
deactivate PartnerDAO
MySQLFactory --> MySQLPartnerDAO : MySQLPartnerDAO()
activate MySQLPartnerDAO
deactivate MySQLFactory


AddUpdatePartnerController --> Admin : Display the view
activate Admin
Admin -> AddUpdatePartnerController : Enter partner information, push the button add
AddUpdatePartnerController -> FacadePartner : submitAddPartner(event)
alt bad info case
    FacadePartner --> AddUpdatePartnerController : throws error
    AddUpdatePartnerController --> Admin : Ask to enter good information
else good info case
    FacadePartner -> MySQLPartnerDAO : submitAddPartner(String lastname, ... ,String company)
    deactivate FacadePartner
    database DB
    MySQLPartnerDAO -> DB : Query Information
    deactivate MySQLPartnerDAO
    AddUpdatePartnerController --> Admin : Display the success of the action
    Admin -> AddUpdatePartnerController : Click "ok"
    deactivate Admin
    AddUpdatePartnerController -> UserRouter : changeView(UserRouter.HOME_ADMIN_PATH_FXML)
    deactivate AddUpdatePartnerController
    deactivate UserRouter
end
@enduml