@startuml
autonumber




activate FacadeUser
FacadeUser -> UserDAO : getInstance()
activate UserDAO
UserDAO -> Factory : getInstance()

activate Factory
Factory --> MySQLFactory : MySQLFactory()
deactivate Factory
activate MySQLFactory
UserDAO -> MySQLFactory : createUserDao()

MySQLFactory --> MySQLUserDAO : MySQLUserDAO()
deactivate MySQLFactory
activate MySQLUserDAO
deactivate MySQLUserDAO



 -> FacadeUser : addPoints(int nbPoints, User user)
FacadeUser -> UserDAO : addPoints(int nbPoints, User user)
@enduml